### ISSUE TITLE
node v0.10.21 support benchmark... support benchmark for node without Promises

### ISSUE THREAD

**Issue by osiyuk** [dfilatov/vow#107]
```
benchmarks $ node -v && node
v0.10.21
> require('../package.json')['engines']
{ node: '>= 0.4.0' }
```

```
benchmarks $ node comparison.js > /dev/null

/home/saradomin/vow/benchmarks/comparison.js:153
                    promise = new Promise(function(_resolve) {
                                  ^
ReferenceError: Promise is not defined
    at /home/saradomin/vow/benchmarks/comparison.js:153:35
    at Array.forEach (native)
    at Object.tests.ES2015 Promise (/home/saradomin/vow/benchmarks/comparison.js:151:31)
    at suite.add.defer (/home/saradomin/vow/benchmarks/comparison.js:259:24)
    at Deferred.d1478380262829711.fn (eval at createCompiled (/home/saradomin/vow/benchmarks/node_modules/benchmark/benchmark.js:1722:16), <anonymous>:4:27)
    at Deferred.eval (eval at createCompiled (/home/saradomin/vow/benchmarks/node_modules/benchmark/benchmark.js:1722:16), <anonymous>:9:65)
    at clock (/home/saradomin/vow/benchmarks/node_modules/benchmark/benchmark.js:1655:29)
    at new Deferred (/home/saradomin/vow/benchmarks/node_modules/benchmark/benchmark.js:405:7)
    at Deferred (/home/saradomin/vow/benchmarks/node_modules/benchmark/benchmark.js:402:16)
    at Benchmark.run (/home/saradomin/vow/benchmarks/node_modules/benchmark/benchmark.js:2109:13)
    at execute (/home/saradomin/vow/benchmarks/node_modules/benchmark/benchmark.js:860:74)
    at null._onTimeout (/home/saradomin/vow/benchmarks/node_modules/lodash/lodash.js:2748:43)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by osiyuk** [comment]
```diff
diff --git a/benchmarks/comparison.js b/benchmarks/comparison.js
index 7950942..f5aaa5e 100644
--- a/benchmarks/comparison.js
+++ b/benchmarks/comparison.js
@@ -235,6 +235,13 @@ var cliff = require('cliff'),
         });
     };
 
+try {
+    new Promise();
+}
+catch (err) {
+    delete tests['ES2015 Promise'];
+}
+
 var suite = new benchmark.Suite(
     'comparison',
     {
@@ -261,7 +268,7 @@ Object.keys(tests).forEach(function(name) {
         {
             defer      : true,
             onStart    : function() {
-                //console.log(name  + ' \n');
+                console.log(name  + ' \n');
             },
             onCycle    : function() {
                 console.log('\033[1A' + new Array(i++).join('.'));
```

Is this ok?

— on node v0.10.21 I`ve got this
```
                mean time ops/sec 
Q               2.611ms   383     
When            0.153ms   6541    
Bluebird        0.353ms   2830    
Pinkie          1.264ms   791     
Davy            0.278ms   3600    
core-js Promise 1.400ms   714     
Vow             0.431ms   2318
```

**Comment by osiyuk** [comment]
@dfilatov Github, please, summon Filatov.

**Comment by dfilatov** [comment]
@osiyuk Do you really need benchmark support of nodejs=0.10.x?

**Comment by osiyuk** [comment]
@dfilatov Sorry, too lazy to upgrade node on my dev laptop. Already done this. #108 
If you want, you can take it, or throw it like a piece of shit. I have tested once and got the result. Probably no one ever wants to do this again.
